language: rust
rust:
  - 1.32.0
  - stable
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
script: ci/script.sh
after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo bench;
    fi
